name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint dpath sqlalchemy==1.4.0b1 pandas pymysql
    - name: Analysing the code with pylint
      run: |
        pylint `find finpandas|grep .py$|xargs`
